Minor change on docs
ARMmbed/mbed-os-example-mbed-crypto pull request #3
Opened 2018-11-28 18:23 UTC by MarceloSalazar

Just a few tweaks to have consistency with other Mbed OS examples

@Patater

2018-11-30 17:23 UTC, Patater requested changes

2018-11-30 17:23 UTC, Patater commented on README.md
> +The following are the steps required for install the application:
Recommend changing "for" to "to".

```diff
- the steps required for install the application
+ the steps required to install the application
```

2018-12-02 10:29 UTC, itayzafrir requested changes
Aside from the comment @Patater left, please fix the redundancy between the `Program your board` and `Run` sections.

2018-12-03 12:07 UTC, MarceloSalazar commented
Fixed. Hopefully is now ok.

2018-12-03 12:20 UTC, MarceloSalazar commented
Let's also update the mbed-os-5.11.0-oob branch

2018-12-03 13:40 UTC, itayzafrir reviewed
One last tweak and then we're good.

2018-12-03 13:40 UTC, itayzafrir commented on README.md
> +1. Connect your mbed device to the computer over USB.
Just for the sake of consistency, maybe capitalize `mbed`
```suggestion
1. Connect your Mbed device to the computer over USB.
```

2018-12-03 14:59 UTC, itayzafrir approved these changes

2018-12-04 10:33 UTC, Patater approved these changes

2018-12-04 10:33 UTC, merged