getting-started: Reduce RSA sign stack usage
ARMmbed/mbed-os-example-mbed-crypto pull request #49
Opened 2019-11-07 18:10 UTC by Patater

On targets with limited stack available to the main thread, our example
can run out of stack space when doing RSA encryption. This can lead to
stack overflows which cause undefined behavior. Move the RSA key and
signature to static RAM instead of stack to reduce the stack footprint
of message signing done by the example.

2019-11-07 18:10 UTC, Patater commented
Tested with ARMC6 and the develop profile. IAR not yet tested.

2019-11-07 18:19 UTC, gilles-peskine-arm requested changes
Ok for the workaround, but this should be documented as a workaround in the code itself, especially since this is in example code.

2019-11-07 18:19 UTC, gilles-peskine-arm commented on getting-started/main.cpp
> +    static uint8_t key[] = RSA_KEY;
Having a `static` variable is unusual, and usually done when the value needs to be preserved between calls, which is not the case here. Please add a comment in the code to indicate why these two variables are `static`.

2019-11-07 18:19 UTC, gilles-peskine-arm commented on getting-started/main.cpp
> +    static uint8_t key[] = RSA_KEY;
Preexisting, but would be nice to do what you're at it: `key` should be `const`.

2019-11-07 18:21 UTC, Patater commented
This is not meant as any sort of workaround. This is meant to reduce stack usage to make the example more portable. We could use a global key instead if use of static in this situation appears uncouth.

2019-11-07 18:24 UTC, Patater commented
New patchset uses `static const` for `key` and adds a comment explaining why the writable `signature` is `static`, as that might be a bit surprising. `static const` is idiomatic enough that it doesn't need a comment.

2019-11-07 18:26 UTC, gilles-peskine-arm approved these changes

2019-11-07 18:27 UTC, Patater commented on getting-started/main.cpp
> +    static uint8_t signature[PSA_ASYMMETRIC_SIGNATURE_MAX_SIZE] = {0};
Making `signature` static is not necessary for the targets we run this example on so far. So, if we dislike adding static here, we can remove it as we don't need it yet. Just making the key `static const` is good enough to pass the tests with ARMC6-develop at least.

2019-11-07 18:30 UTC, Patater commented
Buddy PR at https://github.com/ARMmbed/mbed-crypto/pull/317

2019-11-08 09:28 UTC, dgreen-arm approved these changes
With these changes, the example works with latest Mbed OS using ARMC6 or IAR

2019-11-08 10:33 UTC, Patater commented
New patchset makes the keys global `static const` instead to reduce RAM usage, while also improving the readability of the example.

2019-11-08 10:47 UTC, dgreen-arm approved these changes
Example runs successfully on ARMC6 and IAR, LGTM

2019-11-08 11:00 UTC, gilles-peskine-arm approved these changes

2019-11-08 11:06 UTC, gilles-peskine-arm commented
e46b6adcefcfe0eff770f682f9ca513092cd9751 passed CI with [ARM Compiler reinstated](https://github.com/ARMmbed/mbedtls-test/pull/116) in https://jenkins-internal.mbed.com/job/mbed-crypto-release-ci-testing/577 .

2019-11-08 13:05 UTC, merged